# Generated by Django 5.0.3 on 2024-03-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="teacher",
        ),
        migrations.AddField(
            model_name="student",
            name="teachers",
            field=models.ManyToManyField(related_name="students", to="school.teacher"),
        ),
    ]
