# Generated by Django 5.0.3 on 2024-03-22 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_relationship_tag_relationship_tag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={
                "ordering": ["title"],
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
            },
        ),
    ]
