# Generated by Django 5.0.3 on 2024-03-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phone",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                ("image", models.URLField()),
                ("release_date", models.DateField()),
                ("lte_exist", models.BooleanField()),
                ("slug", models.SlugField(max_length=100)),
            ],
        ),
    ]
