# Generated by Django 5.0.3 on 2024-03-15 21:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("phones", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="phone",
            old_name="lte_exist",
            new_name="lte_exists",
        ),
    ]
